server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/TechRadar # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    url: jdbc:postgresql://db:5432/TechRadar
    #    url: jdbc:postgresql://host.docker.internal:5432/Students
    username: postgres
    password: Kirill2305
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: fgsdffsg456456rertr66yerty56465sdfmk68poiopz